INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_maximum_01020000', '工商银行单笔最大充值金额');
INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_day_maximum_01020000', '工商银行单日最大充值金额');

INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_maximum_01040000', '中国银行单笔最大充值金额');
INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_day_maximum_01040000', '中国银行单日最大充值金额');

INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_maximum_03030000', '光大银行单笔最大充值金额');
INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_day_maximum_03030000', '光大银行单日最大充值金额');

INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_maximum_03090000', '兴业银行单笔最大充值金额');
INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_day_maximum_03090000', '兴业银行单日最大充值金额');

INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_maximum_04100000', '平安银行单笔最大充值金额');
INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_day_maximum_04100000', '平安银行单日最大充值金额');

INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_maximum_03050000', '民生银行单笔最大充值金额');
INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_day_maximum_03050000', '民生银行单日最大充值金额');

INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_maximum_01050000', '建设银行单笔最大充值金额');
INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_day_maximum_01050000', '建设银行单日最大充值金额');

INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_maximum_03020000', '中信银行单笔最大充值金额');
INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_day_maximum_03020000', '中信银行单日最大充值金额');

INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_maximum_01000000', '邮储银行单笔最大充值金额');
INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_day_maximum_01000000', '邮储银行单日最大充值金额');

INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_maximum_01030000', '农业银行单笔最大充值金额');
INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_day_maximum_01030000', '农业银行单日最大充值金额');

INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_maximum_03080000', '招商银行单笔最大充值金额');
INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit_once_day_maximum_03080000', '招商银行单日最大充值金额');


INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_maximum_01020000', 'CNY', 500000, 1);
INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_day_maximum_01020000', 'CNY', 500000, 1);

INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_maximum_01040000', 'CNY', 10000, 1);
INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_day_maximum_01040000', 'CNY', 10000, 1);

INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_maximum_03030000', 'CNY', 500000, 1);
INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_day_maximum_03030000', 'CNY', -1, 1);

INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_maximum_03090000', 'CNY', 500000, 1);
INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_day_maximum_03090000', 'CNY', -1, 1);

INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_maximum_04100000', 'CNY', 500000, 1);
INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_day_maximum_04100000', 'CNY', 5000000, 1);

INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_maximum_03050000', 'CNY', 500000, 1);
INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_day_maximum_03050000', 'CNY', -1, 1);

INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_maximum_01050000', 'CNY', 500000, 1);
INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_day_maximum_01050000', 'CNY', -1, 1);

INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_maximum_03020000', 'CNY', 500000, 1);
INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_day_maximum_03020000', 'CNY', -1, 1);

INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_maximum_01000000', 'CNY', 10000, 1);
INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_day_maximum_01000000', 'CNY', 10000, 1);

INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_maximum_01030000', 'CNY', 20000, 1);
INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_day_maximum_01030000', 'CNY', 20000, 1);

INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_maximum_03080000', 'CNY', 300000, 1);
INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_day_maximum_03080000', 'CNY', -1, 1);

