INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('NUMBER', 'transfer.fee', '转让手续费');

INSERT INTO BIZ_PARAMS_NUMBER (TYPE, KEY_CODE, VALUE, ACTIVE) VALUES ('NUMBER', 'transfer.fee', 0.002, 1);