INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('BOOLEAN', 'auto.settlement', '自动还款');

INSERT INTO BIZ_PARAMS_BOOLEAN (TYPE, KEY_CODE, VALUE, ACTIVE) VALUES ('BOOLEAN', 'auto.settlement', 0, 1);