DELETE FROM BIZ_PARAMS WHERE KEY_CODE = 'deposit_once_maximum_03080000';
DELETE FROM BIZ_PARAMS WHERE KEY_CODE = 'deposit_once_day_maximum_03080000';

INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_maximum_03080000', 'CNY', 300000, 1);
INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_day_maximum_03080000', 'CNY', -1, 1);

INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_maximum_03065840', 'CNY', 500000, 1);
INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit_once_day_maximum_03065840', 'CNY', -1, 1);