CREATE TABLE UMS_AUTHENTICATION_RECORDS (
  ID              BIGINT          PRIMARY KEY AUTO_INCREMENT,
  USER_ID       BIGINT     NOT NULL,
  CERTIFICATE_NAME       VARCHAR(100)    NOT NULL,
  CERTIFICATE_IDENTITY         VARCHAR(64)     NOT NULL,
  BANK_NAME       VARCHAR(50)     NOT NULL DEFAULT '',
  BANK_CODE       VARCHAR(12)     NOT NULL DEFAULT '',
  BANK_ACCOUNT         VARCHAR(32)     NOT NULL DEFAULT '',
  BANK_RESERVED_PHONE           VARCHAR(13)     NOT NULL,
  RESPONSE_CODE     VARCHAR(16) NOT NULL DEFAULT '',
  MESSAGE    VARCHAR(128),
  CREATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;