ALTER TABLE UMS_RELIEVE_BANKCARD_HISITORY ADD NEW_BANK_ACCOUNT VARCHAR(200) NOT NULL;
ALTER TABLE UMS_RELIEVE_BANKCARD_HISITORY ADD APPLY_BY VARCHAR(32) NOT NULL;
ALTER TABLE UMS_RELIEVE_BANKCARD_HISITORY ADD STATUS VARCHAR(10) NOT NULL;
ALTER TABLE UMS_RELIEVE_BANKCARD_HISITORY ADD IS_REBIND VARCHAR(1) NOT NULL;
ALTER TABLE UMS_RELIEVE_BANKCARD_HISITORY CHANGE RELIEVE_BY RECHECK_BY VARCHAR(32) NULL;