INSERT INTO UMS_QUESTIONNAIRES (NAME, ACTIVE) VALUES ('调查问卷', 'ON');

INSERT INTO UMS_QUESTIONS (QUESTIONNAIRE_ID, TITLE) VALUES(1, '您对互联网的使用经验如何：');
INSERT INTO UMS_QUESTIONS (QUESTIONNAIRE_ID, TITLE) VALUES(1, '您的家庭年收入或个人年收入：');
INSERT INTO UMS_QUESTIONS (QUESTIONNAIRE_ID, TITLE) VALUES(1, '在投资期限越长收益越高的前提下，您在投资理财产品时期望的投资期限是多长：');
INSERT INTO UMS_QUESTIONS (QUESTIONNAIRE_ID, TITLE) VALUES(1, '您投资过金融产品都有哪些类别？');
INSERT INTO UMS_QUESTIONS (QUESTIONNAIRE_ID, TITLE) VALUES(1, '您认为您投资中是什么样的风险承担者：');

INSERT INTO UMS_QUESTION_OPTIONS (QUESTION_ID, LABEL, SCORE) VALUES (1, '生活必需', 20);
INSERT INTO UMS_QUESTION_OPTIONS (QUESTION_ID, LABEL, SCORE) VALUES (1, '时常会用', 15);
INSERT INTO UMS_QUESTION_OPTIONS (QUESTION_ID, LABEL, SCORE) VALUES (1, '几乎不会使用', 5);
INSERT INTO UMS_QUESTION_OPTIONS (QUESTION_ID, LABEL, SCORE) VALUES (2, '家庭年收入30万元以下或个人收入20万以下', 5);
INSERT INTO UMS_QUESTION_OPTIONS (QUESTION_ID, LABEL, SCORE) VALUES (2, '家庭年收入30万元-50万元或个人收入20万-50万', 15);
INSERT INTO UMS_QUESTION_OPTIONS (QUESTION_ID, LABEL, SCORE) VALUES (2, '家庭或个人年收入50万元以上', 20);
INSERT INTO UMS_QUESTION_OPTIONS (QUESTION_ID, LABEL, SCORE) VALUES (3, '半年以内，越短越好', 5);
INSERT INTO UMS_QUESTION_OPTIONS (QUESTION_ID, LABEL, SCORE) VALUES (3, '6个月-1年', 15);
INSERT INTO UMS_QUESTION_OPTIONS (QUESTION_ID, LABEL, SCORE) VALUES (3, '1年以上', 20);
INSERT INTO UMS_QUESTION_OPTIONS (QUESTION_ID, LABEL, SCORE) VALUES (4, '除银行存款、国债、银行理财产品外，没有投资过其他金融产品', 5);
INSERT INTO UMS_QUESTION_OPTIONS (QUESTION_ID, LABEL, SCORE) VALUES (4, '购买过股票、债券、公募基金、信托计划、资管计划等产品', 15);
INSERT INTO UMS_QUESTION_OPTIONS (QUESTION_ID, LABEL, SCORE) VALUES (4, '购买过P2P、互联网理财等产品', 20);
INSERT INTO UMS_QUESTION_OPTIONS (QUESTION_ID, LABEL, SCORE) VALUES (5, '无法承担风险', 5);
INSERT INTO UMS_QUESTION_OPTIONS (QUESTION_ID, LABEL, SCORE) VALUES (5, '虽然厌恶风险但愿意承担一些风险', 15);
INSERT INTO UMS_QUESTION_OPTIONS (QUESTION_ID, LABEL, SCORE) VALUES (5, '风险承受能力较强，比较激进', 20);

INSERT INTO UMS_SCORE_LEVELS (SCORE_MIN, SCORE_MAX, RISK_CAPACITY_LEVEL_CODE, RISK_CAPACITY_LEVEL_TEXT) VALUES (30, 59, 'MODERATE', '稳健型');
INSERT INTO UMS_SCORE_LEVELS (SCORE_MIN, SCORE_MAX, RISK_CAPACITY_LEVEL_CODE, RISK_CAPACITY_LEVEL_TEXT) VALUES (60, 999, 'RADICALIZATION', '激进型');
INSERT INTO UMS_SCORE_LEVELS (SCORE_MIN, SCORE_MAX, RISK_CAPACITY_LEVEL_CODE, RISK_CAPACITY_LEVEL_TEXT) VALUES (0, 29, 'CONSERVATISM', '保守型');
