CREATE TABLE UMS_USERS (
  ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
  USER_ID BIGINT UNIQUE NOT NULL  ,
  NAME   VARCHAR(32)  NOT NULL UNIQUE,
  STATUS VARCHAR(32) NOT NULL,
  TYPE VARCHAR(32) NOT NULL ,
  CREATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE TABLE UMS_REGULAR_USERS (
  USER_ID BIGINT NOT NULL,
  PHONE      VARCHAR(13)  NOT NULL,
  PWD VARCHAR(255) NOT NULL,
  CERTIFICATE_NAME VARCHAR(255),
  CERTIFIATE_IDENTITY VARCHAR(255) UNIQUE,
  TRANSACTION_PASSWORD VARCHAR(255)
);

CREATE TABLE UMS_ENTERPRISE_USERS (
  USER_ID         BIGINT NOT NULL,
  ORG_NAME             VARCHAR(255) NOT NULL UNIQUE, /*企业名称*/
  ORG_CODE             VARCHAR(32)  NOT NULL UNIQUE, /*组织机构代码*/

  ORG_ENTITY           VARCHAR(32), /*企业法人*/
  ORG_ENTITY_ID        VARCHAR(255), /*企业法人身份证号*/
  ORG_LICENSE_CODE     VARCHAR(255), /*营业执照编号*/
  ORG_TAX_CODE         VARCHAR(255), /*税务登记证编号*/
  ORG_CAPITAL VARCHAR(64), /*注册资本*/
  ORG_ADDR             VARCHAR(255), /*注册地址*/
  ORG_CONTACT_NAME     VARCHAR(32), /*联系人姓名*/
  ORG_CONTACT_PHONE    VARCHAR(16), /*联系人电话*/
  ORG_CONTACT_EMAIL    VARCHAR(64), /*联系人邮箱*/

  ORG_PROFILE          TEXT /*企业简介*/
);

