CREATE TABLE UMS_QUESTIONNAIRES (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(100) NULL,
  ACTIVE CHAR(3) NOT NULL,
  CREATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE TABLE UMS_QUESTIONS (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  QUESTIONNAIRE_ID BIGINT NOT NULL,
  TITLE VARCHAR (3000) NOT NULL,
  CREATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
ALTER TABLE UMS_QUESTIONS ADD FOREIGN KEY (QUESTIONNAIRE_ID) REFERENCES UMS_QUESTIONNAIRES (ID) ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE TABLE UMS_QUESTION_OPTIONS (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  QUESTION_ID BIGINT NOT NULL,
  LABEL VARCHAR(1000) NOT NULL,
  SCORE INT NOT NULL,
  CREATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
ALTER TABLE UMS_QUESTION_OPTIONS ADD FOREIGN KEY (QUESTION_ID) REFERENCES UMS_QUESTIONS (ID) ON UPDATE CASCADE ON DELETE RESTRICT;

CREATE TABLE UMS_SCORE_LEVELS (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  SCORE_MIN INT NOT NULL,
  SCORE_MAX INT NOT NULL,
  RISK_CAPACITY_LEVEL_CODE VARCHAR(20) UNIQUE NOT NULL,
  RISK_CAPACITY_LEVEL_TEXT VARCHAR(500) NOT NULL,
  CREATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE TABLE UMS_USER_SCORES (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  SCORE INT NOT NULL,
  USER_ID BIGINT NOT NULL,
  RISK_CAPACITY_LEVEL_CODE VARCHAR(20) NOT NULL,
  RISK_CAPACITY_LEVEL_TEXT VARCHAR(500) NOT NULL,
  CREATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
ALTER TABLE UMS_USER_SCORES ADD FOREIGN KEY (RISK_CAPACITY_LEVEL_CODE) REFERENCES UMS_SCORE_LEVELS (RISK_CAPACITY_LEVEL_CODE) ON UPDATE CASCADE ON DELETE RESTRICT;