CREATE TABLE UMS_ADMINS (
  ID         BIGINT PRIMARY KEY    AUTO_INCREMENT,
  NAME       VARCHAR(32)  NOT NULL UNIQUE,
  PWD        VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE TABLE UMS_ADMIN_ROLES (
  ID         BIGINT PRIMARY KEY    AUTO_INCREMENT,
  ADMIN_ID   BIGINT       NOT NULL,
  ROLE_CODE  VARCHAR(64)  NOT NULL,
  ENABLE_AT  TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  DISABLE_AT TIMESTAMP(3) NOT NULL DEFAULT 0,
  ENABLED    NUMERIC(1)   NOT NULL
);