ALTER TABLE UMS_REGULAR_USERS ADD FOREIGN KEY (USER_ID) REFERENCES UMS_USERS (ID) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE UMS_ENTERPRISE_USERS ADD FOREIGN KEY (USER_ID) REFERENCES UMS_USERS (ID) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE UMS_BANK_CARDS ADD FOREIGN KEY (USER_ID) REFERENCES UMS_USERS (ID) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE UMS_ADMIN_ROLES ADD FOREIGN KEY (ADMIN_ID) REFERENCES UMS_ADMINS (ID) ON UPDATE CASCADE ON DELETE RESTRICT;