ALTER TABLE UMS_AUTHENTICATION_RECORDS MODIFY COLUMN BANK_RESERVED_PHONE VARCHAR(13),
                                          ADD COLUMN AUTHENTICATION_TYPE VARCHAR(20),
                                          ADD COLUMN ORD_DATE VARCHAR(12),
                                          ADD COLUMN ORD_SEQID VARCHAR(32);
UPDATE UMS_AUTHENTICATION_RECORDS SET AUTHENTICATION_TYPE="BG_AUTH_TYPE" WHERE AUTHENTICATION_TYPE = "";

