CREATE TABLE UMS_WECHAT_CHANNEL_FANS (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  UMS_USER_ID BIGINT,
  CHANNEL VARCHAR(50) NOT NULL,
  OPENID VARCHAR(255) NOT NULL,
  CREATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);