CREATE TABLE UMS_RELIEVE_BANKCARD_HISITORY (
  ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
  RELIEVE_BY VARCHAR(32) NOT NULL,
  BANKCARD_ID BIGINT NOT NULL ,
  CREATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);