CREATE TABLE UMS_BANK_CARDS (
  ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
  USER_ID BIGINT NOT NULL ,
  BANK_ACCOUNT VARCHAR(200) NOT NULL,
  BANK_CODE    VARCHAR(64)   NOT NULL,
  CREATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);
