CREATE TABLE CP_WITHDRAW_WEEKDAY(
  ID        BIGINT         PRIMARY KEY AUTO_INCREMENT,
  DATE      DATETIME      NOT NULL,
  IS_WEEKDAY    VARCHAR(1)    NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
