UPDATE DEPOSIT_RECORDS SET
CARD_NO = ''
WHERE CARD_NO is NULL AND (CHANNEL = 'YEE_PAY' OR CHANNEL = 'PLATFORM');

UPDATE DEPOSIT_RECORDS SET
BANK_CODE = ''
WHERE BANK_CODE is NULL AND (CHANNEL = 'YEE_PAY' OR CHANNEL = 'PLATFORM');

UPDATE WITHDRAW_RECORDS SET
BANK_NAME = ''
WHERE BANK_NAME is NULL AND (CHANNEL = 'YEE_PAY' OR CHANNEL = 'PLATFORM');

ALTER TABLE DEPOSIT_RECORDS MODIFY CARD_NO VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE DEPOSIT_RECORDS MODIFY BANK_CODE VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE WITHDRAW_RECORDS MODIFY BANK_NAME VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE WITHDRAW_RECORDS MODIFY BANK_CODE VARCHAR(64) NOT NULL DEFAULT '';
ALTER TABLE WITHDRAW_RECORDS MODIFY CARD_NO VARCHAR(64) NOT NULL DEFAULT '';
