DROP TABLE INSTALMENT_TRANSACTIONS;
DROP TABLE INST_ADVANCED_TRANS;

CREATE TABLE TRANSACTIONS (
  ID      BIGINT PRIMARY KEY    AUTO_INCREMENT,
  AP_ID   BIGINT NOT NULL,
  AR_ID   BIGINT NOT NULL,
  FOREIGN KEY (AP_ID) REFERENCES APS (ID),
  FOREIGN KEY (AR_ID) REFERENCES ARS (ID)
);

CREATE TABLE INS_TRANS (
  ID      BIGINT PRIMARY KEY    AUTO_INCREMENT,
  INST_ID BIGINT NOT NULL,
  TRAN_ID BIGINT NOT NULL,
  FOREIGN KEY (INST_ID) REFERENCES INSTALMENTS (ID),
  FOREIGN KEY (TRAN_ID) REFERENCES TRANSACTIONS (ID)
);

CREATE TABLE INS_ADVANCED_TRANS (
  ID      BIGINT PRIMARY KEY    AUTO_INCREMENT,
  INST_ID BIGINT NOT NULL,
  TRAN_ID   BIGINT NOT NULL,
  FOREIGN KEY (INST_ID) REFERENCES INSTALMENTS (ID),
  FOREIGN KEY (TRAN_ID) REFERENCES TRANSACTIONS (ID)
);
