CREATE TABLE CONTRACTS (
  ID          BIGINT PRIMARY KEY    AUTO_INCREMENT,
  EFFECT_DATE TIMESTAMP(3) NOT NULL DEFAULT 0,
  USER_ID     BIGINT       NOT NULL,
  TYPE        VARCHAR(32)  NOT NULL,
  SUBJECT_ID  BIGINT       NOT NULL,
  REP_PLAN_ID BIGINT,
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID)
);

CREATE TABLE REPAYMENT_PLAN (
  ID            BIGINT PRIMARY KEY    AUTO_INCREMENT,
  CREATED_AT    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  COUNTERACT_AT TIMESTAMP(3)          DEFAULT 0
);

CREATE TABLE CON_REPAY_PLAN (
  ID      BIGINT PRIMARY KEY AUTO_INCREMENT,
  CON_ID  BIGINT NOT NULL,
  PLAN_ID BIGINT NOT NULL,
  FOREIGN KEY (CON_ID) REFERENCES CONTRACTS (ID),
  FOREIGN KEY (PLAN_ID) REFERENCES REPAYMENT_PLAN (ID)
);

CREATE TABLE CON_GRANT_PLAN (
  ID      BIGINT PRIMARY KEY AUTO_INCREMENT,
  CON_ID  BIGINT NOT NULL,
  PLAN_ID BIGINT NOT NULL,
  FOREIGN KEY (CON_ID) REFERENCES CONTRACTS (ID),
  FOREIGN KEY (PLAN_ID) REFERENCES REPAYMENT_PLAN (ID)
);

ALTER TABLE CONTRACTS ADD CONSTRAINT CONTRACT_REPAYMENT_PLAN FOREIGN KEY (REP_PLAN_ID) REFERENCES REPAYMENT_PLAN (ID);

CREATE TABLE ADD_CONTRACTS (
  ID                  BIGINT PRIMARY KEY    AUTO_INCREMENT,
  CONTRACT_ID         BIGINT       NOT NULL,
  EFFECT_DATE         TIMESTAMP(3) NOT NULL DEFAULT 0,
  USER_ID             BIGINT,
  TYPE                VARCHAR(32)  NOT NULL,
  INV_ID              BIGINT,
  AGR_ID              BIGINT,
  UNFRO_HIS_ID        BIGINT,
  GRANT_HIS_ID        BIGINT,
  PREPAY_CODE         TEXT,
  OVERDUE_CODE        TEXT,
  FOREIGN KEY (AGR_ID) REFERENCES SUBJECT_AGREEMENTS (ID),
  FOREIGN KEY (INV_ID) REFERENCES INVESTMENT_REQUESTS (ID),
  FOREIGN KEY (UNFRO_HIS_ID) REFERENCES TRANSACTION_HISTORIES (ID),
  FOREIGN KEY (GRANT_HIS_ID) REFERENCES TRANSACTION_HISTORIES (ID)
);

CREATE TABLE APS (
  ID            BIGINT PRIMARY KEY      AUTO_INCREMENT,
  ACCOUNT_ID    BIGINT         NOT NULL,
  CURRENCY      VARCHAR(3)     NOT NULL,
  AMOUNT        NUMERIC(65, 2) NOT NULL,
  STATUS        VARCHAR(16)    NOT NULL,
  PAID_HIS_ID   BIGINT,
  CREATED_AT    TIMESTAMP(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UPDATED_AT    TIMESTAMP(3)   NULL     DEFAULT 0,
  SET_DATE      TIMESTAMP(3)   NOT NULL DEFAULT 0,
  TO_ACCOUNT_ID BIGINT         NOT NULL,
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ID),
  FOREIGN KEY (PAID_HIS_ID) REFERENCES TRANSACTION_HISTORIES (ID),
  FOREIGN KEY (TO_ACCOUNT_ID) REFERENCES ACCOUNTS (ID)
);

CREATE TABLE ARS (
  ID              BIGINT PRIMARY KEY      AUTO_INCREMENT,
  ACCOUNT_ID      BIGINT         NOT NULL,
  FROM_ACCOUNT_ID BIGINT         NOT NULL,
  CURRENCY        VARCHAR(3)     NOT NULL,
  AMOUNT          NUMERIC(65, 2) NOT NULL,
  STATUS          VARCHAR(16)    NOT NULL,
  COL_HIS_ID      BIGINT,
  CREATED_AT      TIMESTAMP(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UPDATED_AT      TIMESTAMP(3)   NULL     DEFAULT 0,
  SET_DATE        TIMESTAMP(3)   NOT NULL DEFAULT 0,
  FOREIGN KEY (COL_HIS_ID) REFERENCES TRANSACTION_HISTORIES (ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ID),
  FOREIGN KEY (FROM_ACCOUNT_ID) REFERENCES ACCOUNTS (ID)
);

CREATE TABLE INSTALMENTS (
  ID             BIGINT PRIMARY KEY    AUTO_INCREMENT,
  CREATED_AT     TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INS_NUMBER     INT          NOT NULL,
  SET_DATE       TIMESTAMP(3) NOT NULL DEFAULT 0,
  EFFECTED_DATE  TIMESTAMP(3) NOT NULL DEFAULT 0,
  REP_PLAN_ID    BIGINT       NOT NULL,
  STATUS         VARCHAR(32)  NOT NULL,
  PRI_ACCOUNT_ID BIGINT       NOT NULL,
  FOREIGN KEY (PRI_ACCOUNT_ID) REFERENCES ACCOUNTS (ID),
  FOREIGN KEY (REP_PLAN_ID) REFERENCES REPAYMENT_PLAN (ID)
);

CREATE TABLE INSTALMENT_TRANSACTIONS (
  ID      BIGINT PRIMARY KEY    AUTO_INCREMENT,
  INST_ID BIGINT NOT NULL,
  AP_ID   BIGINT NOT NULL,
  AR_ID   BIGINT NOT NULL,
  FOREIGN KEY (INST_ID) REFERENCES INSTALMENTS (ID),
  FOREIGN KEY (AP_ID) REFERENCES APS (ID),
  FOREIGN KEY (AR_ID) REFERENCES ARS (ID)
);

CREATE TABLE INST_ADVANCED_TRANS (
  ID      BIGINT PRIMARY KEY    AUTO_INCREMENT,
  INST_ID BIGINT NOT NULL,
  AP_ID   BIGINT NOT NULL,
  AR_ID   BIGINT NOT NULL,
  FOREIGN KEY (INST_ID) REFERENCES INSTALMENTS (ID),
  FOREIGN KEY (AP_ID) REFERENCES APS (ID),
  FOREIGN KEY (AR_ID) REFERENCES ARS (ID)
);

CREATE TABLE ITEMS (
  ID       BIGINT PRIMARY KEY AUTO_INCREMENT,
  AR_ID    BIGINT,
  AP_ID    BIGINT,
  CURRENCY VARCHAR(3)     NOT NULL,
  AMOUNT   NUMERIC(65, 2) NOT NULL,
  TYPE     VARCHAR(256)   NOT NULL,
  FOREIGN KEY (AP_ID) REFERENCES APS (ID),
  FOREIGN KEY (AR_ID) REFERENCES ARS (ID)
);
