ALTER TABLE WITHDRAW_RECORDS ADD COLUMN TYPE VARCHAR(32) DEFAULT 'MANUAL';

ALTER TABLE WITHDRAW_RECORDS ADD COLUMN FEE_CURRENCY VARCHAR(3) NOT NULL DEFAULT 'CNY';
ALTER TABLE WITHDRAW_RECORDS ADD COLUMN FEE_AMOUNT   NUMERIC(65, 2) NOT NULL DEFAULT 0;

CREATE TABLE WITHDRAW_TRANS (
  ID      BIGINT PRIMARY KEY    AUTO_INCREMENT,
  WITHDRAW_ID BIGINT NOT NULL,
  TRAN_ID BIGINT NOT NULL,
  FOREIGN KEY (WITHDRAW_ID) REFERENCES WITHDRAW_RECORDS (ID),
  FOREIGN KEY (TRAN_ID) REFERENCES TRANSACTIONS (ID)
);
