ALTER TABLE DEPOSIT_RECORDS ADD COLUMN CHANNEL VARCHAR(16) NOT NULL;
ALTER TABLE WITHDRAW_RECORDS ADD COLUMN CHANNEL VARCHAR(16) NOT NULL;

UPDATE DEPOSIT_RECORDS SET CHANNEL = "PLATFORM" WHERE TYPE = "MANUAL" AND CHANNEL = "";
UPDATE DEPOSIT_RECORDS SET CHANNEL = "YEE_PAY" WHERE TYPE = "ONLINE" AND CHANNEL = "";
UPDATE WITHDRAW_RECORDS SET CHANNEL = "PLATFORM" WHERE TYPE = "MANUAL" AND CHANNEL = "";
UPDATE WITHDRAW_RECORDS SET CHANNEL = "YEE_PAY" WHERE TYPE = "ONLINE" AND CHANNEL = "";