CREATE TABLE BIZ_PARAMS_BOOLEAN (
  ID          BIGINT PRIMARY KEY      AUTO_INCREMENT,
  TYPE        VARCHAR(50),
  KEY_CODE    VARCHAR(50),
  VALUE TINYINT(1),
  ACTIVE      NUMERIC(1),
  EFFECT_DATE TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);