CREATE TABLE BIZ_PARAMS (
  ID          BIGINT PRIMARY KEY      AUTO_INCREMENT,
  TYPE        VARCHAR(50),
  KEY_CODE    VARCHAR(50),
  CURRENCY    VARCHAR(3)     NOT NULL,
  AMOUNT      NUMERIC(65, 2) NOT NULL,
  ACTIVE      NUMERIC(1),
  EFFECT_DATE TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);