CREATE TABLE INV_REQ_VOUCHERS (
  ID BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  INV_REQ_ID BIGINT NOT NULL,
  VOUCHER_ID BIGINT NOT NULL,
  FOREIGN KEY (INV_REQ_ID) REFERENCES INVESTMENT_REQUESTS (ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  FOREIGN KEY (VOUCHER_ID) REFERENCES VOUCHERS (ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);