ALTER TABLE SUBJECTS ADD TRANSFERABLE TINYINT(1)  NOT NULL DEFAULT 0;
ALTER TABLE SUBJECTS ADD TRANSFERABLE_START_DATE TIMESTAMP(3) NULL DEFAULT NULL;
ALTER TABLE SUBJECTS ADD TRANSFERABLE_END_DATE TIMESTAMP(3) NULL DEFAULT NULL;