ALTER TABLE SUBJECTS ADD ADJUSTMENT_AMOUNT NUMERIC(65, 2)  NULL DEFAULT NULL;
ALTER TABLE SUBJECTS ADD PREV_ADD_CON_ID BIGINT NULL DEFAULT NULL;
ALTER TABLE SUBJECTS ADD ORIG_ADD_CON_ID BIGINT NULL DEFAULT NULL;