CREATE TABLE VOUCHER_TYPES (
	ID BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CHANNEL VARCHAR (241),
	AMOUNT NUMERIC(65, 2) NOT NULL,
	CURRENCY    VARCHAR(3) NOT NULL,
	VALID_DAYS INT NOT NULL,
	VALID TINYINT(1) NOT NULL DEFAULT 1,
	CODE varchar(255) NOT NULL UNIQUE,
	CREATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	UPDATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);