ALTER TABLE DEPOSIT_RECORDS ADD COLUMN FEE_CURRENCY VARCHAR(3) NOT NULL DEFAULT 'CNY';
ALTER TABLE DEPOSIT_RECORDS ADD COLUMN FEE_AMOUNT   NUMERIC(65, 2) NOT NULL DEFAULT 0;

CREATE TABLE DEPOSIT_TRANS (
  ID      BIGINT PRIMARY KEY    AUTO_INCREMENT,
  DEPOSIT_ID BIGINT NOT NULL,
  TRAN_ID BIGINT NOT NULL,
  FOREIGN KEY (DEPOSIT_ID) REFERENCES DEPOSIT_RECORDS (ID),
  FOREIGN KEY (TRAN_ID) REFERENCES TRANSACTIONS (ID)
);
