CREATE TABLE BIZ_PARAMS_REF (
  TYPE        VARCHAR(50),
  KEY_CODE    VARCHAR(50),
  UNIQUE KEY (TYPE, KEY_CODE)
);

ALTER TABLE BIZ_PARAMS ADD FOREIGN KEY (TYPE, KEY_CODE) REFERENCES BIZ_PARAMS_REF(TYPE, KEY_CODE);