ALTER TABLE SUBJECTS MODIFY MIN_INV_CURRENCY VARCHAR(3) NULL DEFAULT NULL;
ALTER TABLE SUBJECTS MODIFY MIN_INV_AMOUNT NUMERIC(65, 2) NULL DEFAULT NULL;
ALTER TABLE SUBJECTS MODIFY STEP_INV_CURRENCY VARCHAR(3) NULL DEFAULT NULL;
ALTER TABLE SUBJECTS MODIFY STEP_INV_AMOUNT NUMERIC(65, 2) NULL DEFAULT NULL;