CREATE TABLE REP_CHANGE_REQ (
  ID               BIGINT PRIMARY KEY    AUTO_INCREMENT,
  CON_ID           BIGINT       NOT NULL,
  COUNTERACT_RP_ID BIGINT,
  TYPE             VARCHAR(32)  NOT NULL,
  STATUS           VARCHAR(32)  NOT NULL,
  CONFIG           TEXT,
  CREATED_AT       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  REJECTED_AT        TIMESTAMP(3)          DEFAULT 0,
  APPROVED_AT       TIMESTAMP(3)          DEFAULT 0,
  FOREIGN KEY (CON_ID) REFERENCES CONTRACTS (ID),
  FOREIGN KEY (COUNTERACT_RP_ID) REFERENCES REPAYMENT_PLAN (ID)
);