CREATE TABLE USER_SUBJECT_VOUCHERS (
  ID BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MIDAS_USER_ID BIGINT NOT NULL,
  SUBJECT_ID BIGINT NOT NULL,
  AMOUNT NUMERIC(65, 2) NOT NULL,
  CURRENCY VARCHAR(3) NOT NULL,
  CREATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UPDATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  FOREIGN KEY (MIDAS_USER_ID) REFERENCES USERS (ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,
  UNIQUE KEY `unique_index`(`MIDAS_USER_ID`, `SUBJECT_ID`)
);