CREATE TABLE SCRIPT_FACTORY (
  ID            BIGINT PRIMARY KEY AUTO_INCREMENT,
  TYPE          VARCHAR(64)    NOT NULL,
  ACTIVE        NUMERIC(1)     NOT NULL,
  CODE          TEXT           NOT NULL,
  CREATED_AT    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
);