CREATE TABLE VOUCHERS (
	ID BIGINT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
	VOUCHER_TYPE_ID BIGINT NOT NULL,
	MIDAS_USER_ID BIGINT NOT NULL,
	STATUS VARCHAR(31) NOT NULL,
	USED_HISTORY_ID BIGINT NULL,
	CREATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	UPDATED_AT TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	FOREIGN KEY (MIDAS_USER_ID) REFERENCES USERS (ID)
		ON UPDATE CASCADE
		ON DELETE RESTRICT,
	FOREIGN KEY (VOUCHER_TYPE_ID) REFERENCES VOUCHER_TYPES (ID)
		ON UPDATE CASCADE
		ON DELETE RESTRICT
);