CREATE TABLE SYNC_RECORDS (
  ID               BIGINT PRIMARY KEY      AUTO_INCREMENT,
  CREATED_AT       TIMESTAMP               DEFAULT CURRENT_TIMESTAMP,
  PAGE             BIGINT         NOT NULL,
  OFFSET           INT            NOT NULL,
  TRAN_ID          BIGINT         NOT NULL,
  FROM_USER_ID     BIGINT         NOT NULL,
  TO_USER_ID       BIGINT         NOT NULL,
  FROM_EXTERNAL_ID VARCHAR(64)    NOT NULL,
  TO_EXTERNAL_ID   VARCHAR(64)    NOT NULL,
  CURRENCY         VARCHAR(3)     NOT NULL,
  AMOUNT           NUMERIC(65, 2) NOT NULL,
  EXTERNAL_RECORD  TEXT           NOT NULL,
  FOREIGN KEY (FROM_USER_ID) REFERENCES USERS (ID),
  FOREIGN KEY (TO_USER_ID) REFERENCES USERS (ID)
);