CREATE TABLE HIS_ITEMS (
  ID      BIGINT PRIMARY KEY AUTO_INCREMENT,
  HIS_ID  BIGINT NOT NULL,
  ITEM_ID BIGINT NOT NULL,
  FOREIGN KEY (HIS_ID) REFERENCES TRANSACTION_HISTORIES (ID),
  FOREIGN KEY (ITEM_ID) REFERENCES ITEMS (ID)
);