CREATE TABLE CP_DEPOSIT_RECORD(
  ID        BIGINT          PRIMARY KEY AUTO_INCREMENT,
  CREATED_AT          DATETIME        NOT NULL,
  BANK_CODE       VARCHAR(16)     NOT NULL,
  BANK_NO         VARCHAR(32)     NOT NULL,
  ORDER_NO        VARCHAR(32)     NOT NULL,
  DEPOSIT_ID      VARCHAR(32)     NOT NULL,
  USER_NAME       VARCHAR(16)     NOT NULL,
  CERT_ID         VARCHAR(64)     NOT NULL,
  USER_ID         VARCHAR(64)     NOT NULL,
  AMOUNT          NUMERIC(15, 2)  NOT NULL,
  SENT_STATUS     VARCHAR(16)     NOT NULL,
  SENT_MESSAGE    VARCHAR(128)    NOT NULL DEFAULT '',
  SENT_AT         DATETIME,
  QUERY_MESSAGE   VARCHAR(128)    NOT NULL DEFAULT '',
  QUERY_AT        DATETIME,
  SYNC_STATUS     VARCHAR(16)     NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
