CREATE TABLE CP_DEPOSIT_SYNC(
  ID              BIGINT    PRIMARY KEY AUTO_INCREMENT,
  SOURCE          VARCHAR(16) NOT NULL,
  PAGE_ID         BIGINT    NOT NULL,
  OFFSET          BIGINT    NOT NULL
)ENGINE=InnoDB DEFAULT CHARSET=utf8;