CREATE TABLE SMS_RECORD (
  ID bigint       PRIMARY KEY AUTO_INCREMENT,
  CREATE_AT       Datetime NOT NULL,
  PLAN_SEND_TIME  Datetime NULL,
  SEND_TIME       Datetime NULL,
  SMS_ID          VARCHAR(64) NULL,
  PHONE           VARCHAR(16) NOT NULL,
  JSON_CONTENT    VARCHAR(512) NOT NULL,
  TEMPLATE_ID     VARCHAR(64) NOT NULL,
  STATUS          VARCHAR(16) NOT NULL,
  RESULT_MESSAGE  VARCHAR(64) NOT NULL DEFAULT ""
)ENGINE=InnoDB DEFAULT CHARSET=utf8;