INSERT INTO BIZ_PARAMS_REF (TYPE, KEY_CODE, DESCRIPTION) VALUES ('MONEY', 'deposit.maximum', '最大充值金额');

INSERT INTO BIZ_PARAMS (TYPE, KEY_CODE, CURRENCY, AMOUNT, ACTIVE) VALUES ('MONEY', 'deposit.maximum', 'CNY', 500000, 1);